-- Cleanup
DROP TABLE IF EXISTS T_COUNTER;
DROP TABLE IF EXISTS T_ORDER_LINE;
DROP TABLE IF EXISTS T_ORDER;
DROP TABLE IF EXISTS T_ITEM;
DROP TABLE IF EXISTS T_PRODUCT;
DROP TABLE IF EXISTS T_CATEGORY;
DROP TABLE IF EXISTS T_CUSTOMER;
DROP TABLE IF EXISTS T_ADDRESS;
DROP TABLE IF EXISTS T_CREDIT_CARD;
